export const SAVE_FUEL_SAVINGS = "SAVE_FUEL_SAVINGS";
export const SAVING_FUEL_SAVINGS = "SAVING_FUEL_SAVINGS";
export const CALCULATE_FUEL_SAVINGS = "CALCULATE_FUEL_SAVINGS";
export const LOAD_FUEL_SAVINGS = "LOAD_FUEL_SAVINGS";
export const LOADING_FUEL_SAVINGS = "LOADING_FUEL_SAVINGS";
